"""et_create_all_tables

Revision ID: 9aa92b82d0a0
Revises: a1c8e6f4b920
Create Date: 2026-08-20 15:44:54.476064

ET 模組 Foundation 建表（#185）——**28 張 ET 業務表**，依 docs/specs/et/data-model.md。

| 群組 | 表 |
|------|----|
| 權限與標籤 | ET_USER_ROLE / ET_TAG / ET_USER_TAG / ET_COURSE_TAG |
| 課程結構 | ET_COURSE / ET_CHAPTER / ET_ITEM / ET_MATERIAL / ET_MATERIAL_VIDEO / ET_MATERIAL_DOC |
| 測驗 | ET_QUIZ / ET_QUESTION / ET_OPTION / ET_QUIZ_ATTEMPT_M / ET_QUIZ_ATTEMPT_D / ET_QUIZ_RETRY_RESET |
| 學習與進度 | ET_ENROLLMENT / ET_PROGRESS / ET_PROGRESS_VIDEO / ET_PROGRESS_INTERVAL |
| 問卷 | ET_SURVEY / ET_SURVEY_QUESTION / ET_SURVEY_OPTION / ET_SURVEY_RESPONSE_M / ET_SURVEY_RESPONSE_D |
| 邀請與稽核 | ET_INVITATION / ET_OWNER_TRANSFER |
| 統計 | ET_WEEKLY_STAT |

**不在本 migration**：`ET_APPROVAL`（線下核可）屬 ET Issue #18，全模組共 29 張。
**不建**：`ET_PARAM` / `ET_NOTIFY_TEMPLATE`（2026-07-08 集中化，改用平台 DP_PARAM /
DP_NOTIFY_TEMPLATE）；9 類 Lookup 代碼表（2026-08-20 定案為應用層常數，見
app/et/constants.py）。

設計要點：
- `USER_ID` / `OWNER_ID` / `EXECUTED_BY` 等為**邏輯 FK** 指向平台 `DP_USER`，
  **不設 DB 外鍵**（跨模組鬆耦合，比照 app/dm/roles/models.py 與 DP 慣例）
- `ET_MATERIAL_DOC.DOC_ID` 為 DM 文件編號 VARCHAR(20)，同樣非 DB 外鍵（經 SRVDM001 查詢）
- append-only 表（`ET_OWNER_TRANSFER` / `ET_QUIZ_RETRY_RESET` / `ET_WEEKLY_STAT`）
  繼承 `AuditLogBaseModel`，僅 CREATED_*、無 UPDATED_* / DELETED
- `ET_ITEM` 之 `ITEM_TYPE` 與 `MATERIAL_ID` / `QUIZ_ID` 互斥，以 CHECK constraint
  `CK_ET_ITEM_TYPE_TARGET` 於 DB 層保證
- `ET_MATERIAL_VIDEO.DURATION_SEC` NOT NULL——覆蓋率公式之分母，取不到不得存檔
- 樂觀鎖 `VERSION`：ET_COURSE / ET_CHAPTER / ET_ITEM / ET_QUIZ / ET_QUESTION / ET_SURVEY*

> 本 migration 一次建齊 28 表（未如 DM #127 拆為 4 支）：Foundation 建表為單一原子操作，
> 拆檔需跨檔處理 FK 順序、徒增出錯面；且全數由 autogenerate 產出並以「重建後 diff 為空」
> 驗證，正確性有機器把關。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa92b82d0a0'
down_revision: Union[str, None] = 'a1c8e6f4b920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ET_COURSE',
    sa.Column('COURSE_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('COURSE_NAME', sa.String(length=100), nullable=False),
    sa.Column('DESCRIPTION', sa.Text(), nullable=True),
    sa.Column('STATUS', sa.String(length=20), nullable=False),
    sa.Column('OPEN_START_AT', sa.DateTime(timezone=True), nullable=True),
    sa.Column('OPEN_END_AT', sa.DateTime(timezone=True), nullable=True),
    sa.Column('OWNER_ID', sa.String(length=20), nullable=False),
    sa.Column('INVITATION_CODE', sa.String(length=8), nullable=True),
    sa.Column('FIRST_PUBLISHED_AT', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CLOSED_AT', sa.DateTime(timezone=True), nullable=True),
    sa.Column('URGENT_REMIND_SENT', sa.Boolean(), nullable=False),
    sa.Column('VERSION', sa.Integer(), nullable=False),
    sa.Column('REQUIRE_APPROVAL', sa.Boolean(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('COURSE_ID', name='PK_ET_COURSE'),
    sa.UniqueConstraint('INVITATION_CODE', name='UQ_ET_COURSE_INVITATION_CODE')
    )
    op.create_index('IX_ET_COURSE_OWNER', 'ET_COURSE', ['OWNER_ID'], unique=False)
    op.create_index('IX_ET_COURSE_STATUS', 'ET_COURSE', ['STATUS'], unique=False)
    op.create_table('ET_MATERIAL',
    sa.Column('MATERIAL_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('MATERIAL_NAME', sa.String(length=100), nullable=False),
    sa.Column('DESCRIPTION_HTML', sa.Text(), nullable=True),
    sa.Column('VERSION', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('MATERIAL_ID', name='PK_ET_MATERIAL')
    )
    op.create_table('ET_QUIZ',
    sa.Column('QUIZ_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('QUIZ_NAME', sa.String(length=100), nullable=False),
    sa.Column('PASS_SCORE', sa.Integer(), nullable=False),
    sa.Column('TIME_LIMIT_MIN', sa.Integer(), nullable=True),
    sa.Column('MAX_RETRY', sa.Integer(), nullable=False),
    sa.Column('VERSION', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('QUIZ_ID', name='PK_ET_QUIZ')
    )
    op.create_table('ET_TAG',
    sa.Column('TAG_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('TAG_NAME', sa.String(length=50), nullable=False),
    sa.Column('IS_ACTIVE', sa.Boolean(), nullable=False),
    sa.Column('IS_ALL', sa.Boolean(), nullable=False),
    sa.Column('IS_BUILTIN', sa.Boolean(), nullable=False),
    sa.Column('DISPLAY_ORDER', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('TAG_ID', name='PK_ET_TAG'),
    sa.UniqueConstraint('TAG_NAME', name='UQ_ET_TAG_NAME')
    )
    op.create_table('ET_USER_ROLE',
    sa.Column('ROLE_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('ROLE', sa.String(length=20), nullable=False),
    sa.Column('IS_ACTIVE', sa.Boolean(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ROLE_ID', name='PK_ET_USER_ROLE'),
    sa.UniqueConstraint('USER_ID', 'ROLE', name='UQ_ET_USER_ROLE_USER_ROLE')
    )
    op.create_index('IX_ET_USER_ROLE_USER', 'ET_USER_ROLE', ['USER_ID'], unique=False)
    op.create_table('ET_CHAPTER',
    sa.Column('CHAPTER_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('COURSE_ID', sa.BigInteger(), nullable=False),
    sa.Column('CHAPTER_NAME', sa.String(length=100), nullable=False),
    sa.Column('SORT_ORDER', sa.Integer(), nullable=False),
    sa.Column('VERSION', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['COURSE_ID'], ['ET_COURSE.COURSE_ID'], name='FK_ET_CHAPTER_COURSE'),
    sa.PrimaryKeyConstraint('CHAPTER_ID', name='PK_ET_CHAPTER'),
    sa.UniqueConstraint('COURSE_ID', 'SORT_ORDER', name='UQ_ET_CHAPTER_COURSE_ORDER')
    )
    op.create_table('ET_COURSE_TAG',
    sa.Column('COURSE_TAG_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('COURSE_ID', sa.BigInteger(), nullable=False),
    sa.Column('TAG_ID', sa.BigInteger(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['COURSE_ID'], ['ET_COURSE.COURSE_ID'], name='FK_ET_COURSE_TAG_COURSE'),
    sa.ForeignKeyConstraint(['TAG_ID'], ['ET_TAG.TAG_ID'], name='FK_ET_COURSE_TAG_TAG'),
    sa.PrimaryKeyConstraint('COURSE_TAG_ID', name='PK_ET_COURSE_TAG'),
    sa.UniqueConstraint('COURSE_ID', 'TAG_ID', name='UQ_ET_COURSE_TAG_COURSE_TAG')
    )
    op.create_index('IX_ET_COURSE_TAG_TAG', 'ET_COURSE_TAG', ['TAG_ID'], unique=False)
    op.create_table('ET_ENROLLMENT',
    sa.Column('ENROLLMENT_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('COURSE_ID', sa.BigInteger(), nullable=False),
    sa.Column('JOIN_SOURCE', sa.String(length=30), nullable=False),
    sa.Column('JOINED_AT', sa.DateTime(timezone=True), nullable=False),
    sa.Column('COMPLETION_STATUS', sa.String(length=20), nullable=False),
    sa.Column('COMPLETED_AT', sa.DateTime(timezone=True), nullable=True),
    sa.Column('IS_REMOVED', sa.Boolean(), nullable=False),
    sa.Column('REMOVED_AT', sa.DateTime(timezone=True), nullable=True),
    sa.Column('LAST_ACTIVITY_AT', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['COURSE_ID'], ['ET_COURSE.COURSE_ID'], name='FK_ET_ENROLLMENT_COURSE'),
    sa.PrimaryKeyConstraint('ENROLLMENT_ID', name='PK_ET_ENROLLMENT'),
    sa.UniqueConstraint('USER_ID', 'COURSE_ID', name='UQ_ET_ENROLLMENT_USER_COURSE')
    )
    op.create_index('IX_ET_ENROLLMENT_COURSE', 'ET_ENROLLMENT', ['COURSE_ID'], unique=False)
    op.create_table('ET_INVITATION',
    sa.Column('INVITATION_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('COURSE_ID', sa.BigInteger(), nullable=False),
    sa.Column('EMAIL', sa.String(length=255), nullable=False),
    sa.Column('TOKEN', sa.String(length=64), nullable=False),
    sa.Column('STATUS', sa.String(length=20), nullable=False),
    sa.Column('SENT_AT', sa.DateTime(timezone=True), nullable=False),
    sa.Column('LAST_SENT_AT', sa.DateTime(timezone=True), nullable=False),
    sa.Column('JOINED_AT', sa.DateTime(timezone=True), nullable=True),
    sa.Column('REVOKED_AT', sa.DateTime(timezone=True), nullable=True),
    sa.Column('SEND_STATUS_CODE', sa.String(length=20), nullable=True),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['COURSE_ID'], ['ET_COURSE.COURSE_ID'], name='FK_ET_INVITATION_COURSE'),
    sa.PrimaryKeyConstraint('INVITATION_ID', name='PK_ET_INVITATION'),
    sa.UniqueConstraint('TOKEN', name='UQ_ET_INVITATION_TOKEN')
    )
    op.create_index('IX_ET_INVITATION_COURSE', 'ET_INVITATION', ['COURSE_ID'], unique=False)
    op.create_table('ET_MATERIAL_DOC',
    sa.Column('MAT_DOC_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('MATERIAL_ID', sa.BigInteger(), nullable=False),
    sa.Column('DOC_ID', sa.String(length=20), nullable=False),
    sa.Column('SORT_ORDER', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MATERIAL_ID'], ['ET_MATERIAL.MATERIAL_ID'], name='FK_ET_MATERIAL_DOC_MATERIAL'),
    sa.PrimaryKeyConstraint('MAT_DOC_ID', name='PK_ET_MATERIAL_DOC'),
    sa.UniqueConstraint('MATERIAL_ID', 'DOC_ID', name='UQ_ET_MATERIAL_DOC_MATERIAL_DOC')
    )
    op.create_table('ET_MATERIAL_VIDEO',
    sa.Column('VIDEO_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('MATERIAL_ID', sa.BigInteger(), nullable=False),
    sa.Column('FILE_PATH', sa.String(length=500), nullable=False),
    sa.Column('FILE_NAME', sa.String(length=200), nullable=False),
    sa.Column('DURATION_SEC', sa.Integer(), nullable=False),
    sa.Column('FILE_SIZE_BYTES', sa.BigInteger(), nullable=False),
    sa.Column('SORT_ORDER', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MATERIAL_ID'], ['ET_MATERIAL.MATERIAL_ID'], name='FK_ET_MATERIAL_VIDEO_MATERIAL'),
    sa.PrimaryKeyConstraint('VIDEO_ID', name='PK_ET_MATERIAL_VIDEO'),
    sa.UniqueConstraint('MATERIAL_ID', 'SORT_ORDER', name='UQ_ET_MATERIAL_VIDEO_ORDER')
    )
    op.create_table('ET_OWNER_TRANSFER',
    sa.Column('TRANSFER_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('COURSE_ID', sa.BigInteger(), nullable=False),
    sa.Column('FROM_OWNER_ID', sa.String(length=20), nullable=False),
    sa.Column('TO_OWNER_ID', sa.String(length=20), nullable=False),
    sa.Column('REASON', sa.Text(), nullable=False),
    sa.Column('EXECUTED_BY', sa.String(length=20), nullable=False),
    sa.Column('EXECUTED_AT', sa.DateTime(timezone=True), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['COURSE_ID'], ['ET_COURSE.COURSE_ID'], name='FK_ET_OWNER_TRANSFER_COURSE'),
    sa.PrimaryKeyConstraint('TRANSFER_ID', name='PK_ET_OWNER_TRANSFER')
    )
    op.create_index('IX_ET_OWNER_TRANSFER_COURSE', 'ET_OWNER_TRANSFER', ['COURSE_ID'], unique=False)
    op.create_table('ET_QUESTION',
    sa.Column('QUESTION_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('QUIZ_ID', sa.BigInteger(), nullable=False),
    sa.Column('QUESTION_TYPE', sa.String(length=20), nullable=False),
    sa.Column('STEM', sa.String(length=500), nullable=False),
    sa.Column('POINTS', sa.Integer(), nullable=False),
    sa.Column('SORT_ORDER', sa.Integer(), nullable=False),
    sa.Column('VERSION', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['QUIZ_ID'], ['ET_QUIZ.QUIZ_ID'], name='FK_ET_QUESTION_QUIZ'),
    sa.PrimaryKeyConstraint('QUESTION_ID', name='PK_ET_QUESTION')
    )
    op.create_index('IX_ET_QUESTION_QUIZ', 'ET_QUESTION', ['QUIZ_ID'], unique=False)
    op.create_table('ET_QUIZ_ATTEMPT_M',
    sa.Column('ATTEMPT_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('COURSE_ID', sa.BigInteger(), nullable=False),
    sa.Column('QUIZ_ID', sa.BigInteger(), nullable=False),
    sa.Column('ATTEMPT_NO', sa.Integer(), nullable=False),
    sa.Column('STARTED_AT', sa.DateTime(timezone=True), nullable=False),
    sa.Column('SUBMITTED_AT', sa.DateTime(timezone=True), nullable=True),
    sa.Column('STATUS', sa.String(length=20), nullable=False),
    sa.Column('SCORE', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('IS_PASS', sa.Boolean(), nullable=True),
    sa.Column('QUESTION_ORDER', sa.Text(), nullable=False),
    sa.Column('OPTION_ORDER', sa.Text(), nullable=False),
    sa.Column('PASS_SCORE_SNAPSHOT', sa.Integer(), nullable=False),
    sa.Column('TIME_LIMIT_SNAPSHOT', sa.Integer(), nullable=True),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['COURSE_ID'], ['ET_COURSE.COURSE_ID'], name='FK_ET_ATTEMPT_COURSE'),
    sa.ForeignKeyConstraint(['QUIZ_ID'], ['ET_QUIZ.QUIZ_ID'], name='FK_ET_ATTEMPT_QUIZ'),
    sa.PrimaryKeyConstraint('ATTEMPT_ID', name='PK_ET_QUIZ_ATTEMPT_M'),
    sa.UniqueConstraint('USER_ID', 'QUIZ_ID', 'ATTEMPT_NO', name='UQ_ET_ATTEMPT_USER_QUIZ_NO')
    )
    op.create_index('IX_ET_ATTEMPT_COURSE', 'ET_QUIZ_ATTEMPT_M', ['COURSE_ID'], unique=False)
    op.create_index('IX_ET_ATTEMPT_USER_QUIZ', 'ET_QUIZ_ATTEMPT_M', ['USER_ID', 'QUIZ_ID'], unique=False)
    op.create_table('ET_QUIZ_RETRY_RESET',
    sa.Column('RESET_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('QUIZ_ID', sa.BigInteger(), nullable=False),
    sa.Column('COURSE_ID', sa.BigInteger(), nullable=False),
    sa.Column('ATTEMPT_COUNT_AT_RESET', sa.Integer(), nullable=False),
    sa.Column('EXECUTED_BY', sa.String(length=20), nullable=False),
    sa.Column('EXECUTED_AT', sa.DateTime(timezone=True), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['COURSE_ID'], ['ET_COURSE.COURSE_ID'], name='FK_ET_RETRY_RESET_COURSE'),
    sa.ForeignKeyConstraint(['QUIZ_ID'], ['ET_QUIZ.QUIZ_ID'], name='FK_ET_RETRY_RESET_QUIZ'),
    sa.PrimaryKeyConstraint('RESET_ID', name='PK_ET_QUIZ_RETRY_RESET')
    )
    op.create_index('IX_ET_RETRY_RESET_USER_QUIZ', 'ET_QUIZ_RETRY_RESET', ['USER_ID', 'QUIZ_ID'], unique=False)
    op.create_table('ET_SURVEY',
    sa.Column('SURVEY_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('COURSE_ID', sa.BigInteger(), nullable=False),
    sa.Column('SURVEY_NAME', sa.String(length=100), nullable=False),
    sa.Column('IS_ACTIVE', sa.Boolean(), nullable=False),
    sa.Column('VERSION', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['COURSE_ID'], ['ET_COURSE.COURSE_ID'], name='FK_ET_SURVEY_COURSE'),
    sa.PrimaryKeyConstraint('SURVEY_ID', name='PK_ET_SURVEY'),
    sa.UniqueConstraint('COURSE_ID', name='UQ_ET_SURVEY_COURSE')
    )
    op.create_table('ET_USER_TAG',
    sa.Column('USER_TAG_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('TAG_ID', sa.BigInteger(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['TAG_ID'], ['ET_TAG.TAG_ID'], name='FK_ET_USER_TAG_TAG'),
    sa.PrimaryKeyConstraint('USER_TAG_ID', name='PK_ET_USER_TAG'),
    sa.UniqueConstraint('USER_ID', 'TAG_ID', name='UQ_ET_USER_TAG_USER_TAG')
    )
    op.create_index('IX_ET_USER_TAG_USER', 'ET_USER_TAG', ['USER_ID'], unique=False)
    op.create_table('ET_WEEKLY_STAT',
    sa.Column('STAT_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('COURSE_ID', sa.BigInteger(), nullable=False),
    sa.Column('STAT_DATE', sa.Date(), nullable=False),
    sa.Column('AVG_PROGRESS_PCT', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('CNT_NOT_STARTED', sa.Integer(), nullable=False),
    sa.Column('CNT_IN_PROGRESS', sa.Integer(), nullable=False),
    sa.Column('CNT_COMPLETED', sa.Integer(), nullable=False),
    sa.Column('COMPLETION_RATE', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('CNT_ENROLLED', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['COURSE_ID'], ['ET_COURSE.COURSE_ID'], name='FK_ET_WEEKLY_STAT_COURSE'),
    sa.PrimaryKeyConstraint('STAT_ID', name='PK_ET_WEEKLY_STAT'),
    sa.UniqueConstraint('COURSE_ID', 'STAT_DATE', name='UQ_ET_WEEKLY_STAT_COURSE_DATE')
    )
    op.create_table('ET_ITEM',
    sa.Column('ITEM_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('CHAPTER_ID', sa.BigInteger(), nullable=False),
    sa.Column('ITEM_TYPE', sa.String(length=20), nullable=False),
    sa.Column('SORT_ORDER', sa.Integer(), nullable=False),
    sa.Column('MATERIAL_ID', sa.BigInteger(), nullable=True),
    sa.Column('QUIZ_ID', sa.BigInteger(), nullable=True),
    sa.Column('VERSION', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.CheckConstraint('("ITEM_TYPE" = \'MATERIAL\' AND "MATERIAL_ID" IS NOT NULL AND "QUIZ_ID" IS NULL) OR ("ITEM_TYPE" = \'QUIZ\' AND "QUIZ_ID" IS NOT NULL AND "MATERIAL_ID" IS NULL)', name='CK_ET_ITEM_TYPE_TARGET'),
    sa.ForeignKeyConstraint(['CHAPTER_ID'], ['ET_CHAPTER.CHAPTER_ID'], name='FK_ET_ITEM_CHAPTER'),
    sa.ForeignKeyConstraint(['MATERIAL_ID'], ['ET_MATERIAL.MATERIAL_ID'], name='FK_ET_ITEM_MATERIAL'),
    sa.ForeignKeyConstraint(['QUIZ_ID'], ['ET_QUIZ.QUIZ_ID'], name='FK_ET_ITEM_QUIZ'),
    sa.PrimaryKeyConstraint('ITEM_ID', name='PK_ET_ITEM'),
    sa.UniqueConstraint('CHAPTER_ID', 'SORT_ORDER', name='UQ_ET_ITEM_CHAPTER_ORDER')
    )
    op.create_table('ET_OPTION',
    sa.Column('OPTION_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('QUESTION_ID', sa.BigInteger(), nullable=False),
    sa.Column('OPTION_TEXT', sa.String(length=200), nullable=False),
    sa.Column('IS_CORRECT', sa.Boolean(), nullable=False),
    sa.Column('SORT_ORDER', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['QUESTION_ID'], ['ET_QUESTION.QUESTION_ID'], name='FK_ET_OPTION_QUESTION'),
    sa.PrimaryKeyConstraint('OPTION_ID', name='PK_ET_OPTION')
    )
    op.create_index('IX_ET_OPTION_QUESTION', 'ET_OPTION', ['QUESTION_ID'], unique=False)
    op.create_table('ET_PROGRESS_INTERVAL',
    sa.Column('INTERVAL_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('VIDEO_ID', sa.BigInteger(), nullable=False),
    sa.Column('START_SEC', sa.Integer(), nullable=False),
    sa.Column('END_SEC', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['VIDEO_ID'], ['ET_MATERIAL_VIDEO.VIDEO_ID'], name='FK_ET_PROGRESS_INTERVAL_VIDEO'),
    sa.PrimaryKeyConstraint('INTERVAL_ID', name='PK_ET_PROGRESS_INTERVAL')
    )
    op.create_index('IX_ET_PROGRESS_INTERVAL_USER_VIDEO', 'ET_PROGRESS_INTERVAL', ['USER_ID', 'VIDEO_ID'], unique=False)
    op.create_table('ET_PROGRESS_VIDEO',
    sa.Column('PROGRESS_VIDEO_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('VIDEO_ID', sa.BigInteger(), nullable=False),
    sa.Column('COVERAGE_PCT', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('LAST_POSITION_SEC', sa.Integer(), nullable=True),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['VIDEO_ID'], ['ET_MATERIAL_VIDEO.VIDEO_ID'], name='FK_ET_PROGRESS_VIDEO_VIDEO'),
    sa.PrimaryKeyConstraint('PROGRESS_VIDEO_ID', name='PK_ET_PROGRESS_VIDEO'),
    sa.UniqueConstraint('USER_ID', 'VIDEO_ID', name='UQ_ET_PROGRESS_VIDEO_USER_VIDEO')
    )
    op.create_table('ET_QUIZ_ATTEMPT_D',
    sa.Column('DETAIL_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ATTEMPT_ID', sa.BigInteger(), nullable=False),
    sa.Column('QUESTION_ID', sa.BigInteger(), nullable=False),
    sa.Column('STEM_SNAPSHOT', sa.String(length=500), nullable=False),
    sa.Column('POINTS_SNAPSHOT', sa.Integer(), nullable=False),
    sa.Column('TYPE_SNAPSHOT', sa.String(length=20), nullable=False),
    sa.Column('OPTIONS_SNAPSHOT', sa.Text(), nullable=False),
    sa.Column('SELECTED_OPTIONS', sa.Text(), nullable=True),
    sa.Column('SCORE', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ATTEMPT_ID'], ['ET_QUIZ_ATTEMPT_M.ATTEMPT_ID'], name='FK_ET_ATTEMPT_D_ATTEMPT'),
    sa.ForeignKeyConstraint(['QUESTION_ID'], ['ET_QUESTION.QUESTION_ID'], name='FK_ET_ATTEMPT_D_QUESTION'),
    sa.PrimaryKeyConstraint('DETAIL_ID', name='PK_ET_QUIZ_ATTEMPT_D'),
    sa.UniqueConstraint('ATTEMPT_ID', 'QUESTION_ID', name='UQ_ET_ATTEMPT_D_ATTEMPT_QUESTION')
    )
    op.create_table('ET_SURVEY_QUESTION',
    sa.Column('SQ_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('SURVEY_ID', sa.BigInteger(), nullable=False),
    sa.Column('STEM', sa.String(length=500), nullable=False),
    sa.Column('SORT_ORDER', sa.Integer(), nullable=False),
    sa.Column('VERSION', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['SURVEY_ID'], ['ET_SURVEY.SURVEY_ID'], name='FK_ET_SURVEY_QUESTION_SURVEY'),
    sa.PrimaryKeyConstraint('SQ_ID', name='PK_ET_SURVEY_QUESTION'),
    sa.UniqueConstraint('SURVEY_ID', 'SORT_ORDER', name='UQ_ET_SURVEY_QUESTION_ORDER')
    )
    op.create_table('ET_SURVEY_RESPONSE_M',
    sa.Column('RESPONSE_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('SURVEY_ID', sa.BigInteger(), nullable=False),
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('SUBMITTED_AT', sa.DateTime(timezone=True), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['SURVEY_ID'], ['ET_SURVEY.SURVEY_ID'], name='FK_ET_SURVEY_RESPONSE_SURVEY'),
    sa.PrimaryKeyConstraint('RESPONSE_ID', name='PK_ET_SURVEY_RESPONSE_M'),
    sa.UniqueConstraint('SURVEY_ID', 'USER_ID', name='UQ_ET_SURVEY_RESPONSE_SURVEY_USER')
    )
    op.create_index('IX_ET_SURVEY_RESPONSE_USER', 'ET_SURVEY_RESPONSE_M', ['USER_ID'], unique=False)
    op.create_table('ET_PROGRESS',
    sa.Column('PROGRESS_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('COURSE_ID', sa.BigInteger(), nullable=False),
    sa.Column('ITEM_ID', sa.BigInteger(), nullable=False),
    sa.Column('IS_COMPLETED', sa.Boolean(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['COURSE_ID'], ['ET_COURSE.COURSE_ID'], name='FK_ET_PROGRESS_COURSE'),
    sa.ForeignKeyConstraint(['ITEM_ID'], ['ET_ITEM.ITEM_ID'], name='FK_ET_PROGRESS_ITEM'),
    sa.PrimaryKeyConstraint('PROGRESS_ID', name='PK_ET_PROGRESS'),
    sa.UniqueConstraint('USER_ID', 'ITEM_ID', name='UQ_ET_PROGRESS_USER_ITEM')
    )
    op.create_index('IX_ET_PROGRESS_COURSE', 'ET_PROGRESS', ['COURSE_ID'], unique=False)
    op.create_table('ET_SURVEY_OPTION',
    sa.Column('SO_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('SQ_ID', sa.BigInteger(), nullable=False),
    sa.Column('OPTION_TEXT', sa.String(length=200), nullable=False),
    sa.Column('SORT_ORDER', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['SQ_ID'], ['ET_SURVEY_QUESTION.SQ_ID'], name='FK_ET_SURVEY_OPTION_QUESTION'),
    sa.PrimaryKeyConstraint('SO_ID', name='PK_ET_SURVEY_OPTION'),
    sa.UniqueConstraint('SQ_ID', 'SORT_ORDER', name='UQ_ET_SURVEY_OPTION_ORDER')
    )
    op.create_table('ET_SURVEY_RESPONSE_D',
    sa.Column('RD_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('RESPONSE_ID', sa.BigInteger(), nullable=False),
    sa.Column('SQ_ID', sa.BigInteger(), nullable=False),
    sa.Column('SO_ID', sa.BigInteger(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RESPONSE_ID'], ['ET_SURVEY_RESPONSE_M.RESPONSE_ID'], name='FK_ET_SURVEY_RESPONSE_D_RESPONSE'),
    sa.ForeignKeyConstraint(['SO_ID'], ['ET_SURVEY_OPTION.SO_ID'], name='FK_ET_SURVEY_RESPONSE_D_OPTION'),
    sa.ForeignKeyConstraint(['SQ_ID'], ['ET_SURVEY_QUESTION.SQ_ID'], name='FK_ET_SURVEY_RESPONSE_D_QUESTION'),
    sa.PrimaryKeyConstraint('RD_ID', name='PK_ET_SURVEY_RESPONSE_D'),
    sa.UniqueConstraint('RESPONSE_ID', 'SQ_ID', name='UQ_ET_SURVEY_RESPONSE_D_RESPONSE_Q')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ET_SURVEY_RESPONSE_D')
    op.drop_table('ET_SURVEY_OPTION')
    op.drop_index('IX_ET_PROGRESS_COURSE', table_name='ET_PROGRESS')
    op.drop_table('ET_PROGRESS')
    op.drop_index('IX_ET_SURVEY_RESPONSE_USER', table_name='ET_SURVEY_RESPONSE_M')
    op.drop_table('ET_SURVEY_RESPONSE_M')
    op.drop_table('ET_SURVEY_QUESTION')
    op.drop_table('ET_QUIZ_ATTEMPT_D')
    op.drop_table('ET_PROGRESS_VIDEO')
    op.drop_index('IX_ET_PROGRESS_INTERVAL_USER_VIDEO', table_name='ET_PROGRESS_INTERVAL')
    op.drop_table('ET_PROGRESS_INTERVAL')
    op.drop_index('IX_ET_OPTION_QUESTION', table_name='ET_OPTION')
    op.drop_table('ET_OPTION')
    op.drop_table('ET_ITEM')
    op.drop_table('ET_WEEKLY_STAT')
    op.drop_index('IX_ET_USER_TAG_USER', table_name='ET_USER_TAG')
    op.drop_table('ET_USER_TAG')
    op.drop_table('ET_SURVEY')
    op.drop_index('IX_ET_RETRY_RESET_USER_QUIZ', table_name='ET_QUIZ_RETRY_RESET')
    op.drop_table('ET_QUIZ_RETRY_RESET')
    op.drop_index('IX_ET_ATTEMPT_USER_QUIZ', table_name='ET_QUIZ_ATTEMPT_M')
    op.drop_index('IX_ET_ATTEMPT_COURSE', table_name='ET_QUIZ_ATTEMPT_M')
    op.drop_table('ET_QUIZ_ATTEMPT_M')
    op.drop_index('IX_ET_QUESTION_QUIZ', table_name='ET_QUESTION')
    op.drop_table('ET_QUESTION')
    op.drop_index('IX_ET_OWNER_TRANSFER_COURSE', table_name='ET_OWNER_TRANSFER')
    op.drop_table('ET_OWNER_TRANSFER')
    op.drop_table('ET_MATERIAL_VIDEO')
    op.drop_table('ET_MATERIAL_DOC')
    op.drop_index('IX_ET_INVITATION_COURSE', table_name='ET_INVITATION')
    op.drop_table('ET_INVITATION')
    op.drop_index('IX_ET_ENROLLMENT_COURSE', table_name='ET_ENROLLMENT')
    op.drop_table('ET_ENROLLMENT')
    op.drop_index('IX_ET_COURSE_TAG_TAG', table_name='ET_COURSE_TAG')
    op.drop_table('ET_COURSE_TAG')
    op.drop_table('ET_CHAPTER')
    op.drop_index('IX_ET_USER_ROLE_USER', table_name='ET_USER_ROLE')
    op.drop_table('ET_USER_ROLE')
    op.drop_table('ET_TAG')
    op.drop_table('ET_QUIZ')
    op.drop_table('ET_MATERIAL')
    op.drop_index('IX_ET_COURSE_STATUS', table_name='ET_COURSE')
    op.drop_index('IX_ET_COURSE_OWNER', table_name='ET_COURSE')
    op.drop_table('ET_COURSE')
    # ### end Alembic commands ###
