"""dp_create_schedule_tables

Revision ID: 5065c9fdf7e4
Revises: 53ffc92cab2d
Create Date: 2026-07-14 14:27:21.328098

建立 DP_SCHEDULE 與 DP_SCHEDULE_LOG（排程註冊表 + 執行歷程）。

異動說明：
- 影響 Table：DP_SCHEDULE（新增）、DP_SCHEDULE_LOG（新增，append-only 僅 CREATED_*）
- DP_SCHEDULE：JOB_ID PK（PK_DP_SCHEDULE）、BaseModel 標準欄位
- DP_SCHEDULE_LOG：LOG_ID BIGINT Identity PK（PK_DP_SCHEDULE_LOG）、
  FK_DP_SCHEDULE_LOG_JOB→DP_SCHEDULE、索引 IX_DP_SCHEDULE_LOG_JOB_START
- 完成 DP 10 張平台表最後一批；排程 job 4 筆種子屬 T009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5065c9fdf7e4'
down_revision: Union[str, None] = '53ffc92cab2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DP_SCHEDULE',
    sa.Column('JOB_ID', sa.String(length=20), nullable=False),
    sa.Column('JOB_NAME', sa.String(length=100), nullable=False),
    sa.Column('MODULE', sa.String(length=5), nullable=False),
    sa.Column('CRON_EXPR', sa.String(length=50), nullable=False),
    sa.Column('HANDLER_REF', sa.String(length=200), nullable=False),
    sa.Column('IS_ENABLED', sa.Boolean(), nullable=False),
    sa.Column('LAST_RUN_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('LAST_RUN_STATUS', sa.String(length=10), nullable=True),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('RES_ID', sa.String(length=30), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('JOB_ID', name='PK_DP_SCHEDULE')
    )
    op.create_table('DP_SCHEDULE_LOG',
    sa.Column('LOG_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('JOB_ID', sa.String(length=20), nullable=False),
    sa.Column('START_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('END_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('STATUS', sa.String(length=10), nullable=False),
    sa.Column('ERROR_MSG', sa.String(length=1000), nullable=True),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['JOB_ID'], ['DP_SCHEDULE.JOB_ID'], name='FK_DP_SCHEDULE_LOG_JOB'),
    sa.PrimaryKeyConstraint('LOG_ID', name='PK_DP_SCHEDULE_LOG')
    )
    op.create_index('IX_DP_SCHEDULE_LOG_JOB_START', 'DP_SCHEDULE_LOG', ['JOB_ID', 'START_DATE'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IX_DP_SCHEDULE_LOG_JOB_START', table_name='DP_SCHEDULE_LOG')
    op.drop_table('DP_SCHEDULE_LOG')
    op.drop_table('DP_SCHEDULE')
    # ### end Alembic commands ###
