"""dm_create_catalog_tables

Revision ID: 2d877f07412e
Revises: df37b7ba16b3
Create Date: 2026-08-06 10:31:14.101871

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d877f07412e"
down_revision: Union[str, None] = "df37b7ba16b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DM_CATEGORY",
        sa.Column("CATEGORY_CODE", sa.String(length=10), nullable=False),
        sa.Column("CATEGORY_NAME", sa.String(length=50), nullable=False),
        sa.Column("IS_BUILTIN", sa.Boolean(), nullable=False),
        sa.Column("IS_ENABLED", sa.Boolean(), nullable=False),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.Column("UPDATED_USER", sa.String(length=20), nullable=True),
        sa.Column("UPDATED_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("DELETED", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("CATEGORY_CODE", name="PK_DM_CATEGORY"),
    )
    op.create_table(
        "DM_FUNC",
        sa.Column("FUNC_CODE", sa.String(length=10), nullable=False),
        sa.Column("FUNC_NAME", sa.String(length=100), nullable=False),
        sa.Column("IS_ENABLED", sa.Boolean(), nullable=False),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.Column("UPDATED_USER", sa.String(length=20), nullable=True),
        sa.Column("UPDATED_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("DELETED", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("FUNC_CODE", name="PK_DM_FUNC"),
    )
    op.create_table(
        "DM_TAG_GROUP",
        sa.Column("TAG_GROUP_CODE", sa.String(length=20), nullable=False),
        sa.Column("TAG_GROUP_NAME", sa.String(length=50), nullable=False),
        sa.Column("GROUP_TYPE", sa.String(length=10), nullable=False),
        sa.Column("IS_BUILTIN", sa.Boolean(), nullable=False),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.Column("UPDATED_USER", sa.String(length=20), nullable=True),
        sa.Column("UPDATED_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("DELETED", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("TAG_GROUP_CODE", name="PK_DM_TAG_GROUP"),
    )
    op.create_table(
        "DM_TAG",
        sa.Column("TAG_ID", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("TAG_GROUP_CODE", sa.String(length=20), nullable=False),
        sa.Column("TAG_NAME", sa.String(length=50), nullable=False),
        sa.Column("IS_ENABLED", sa.Boolean(), nullable=False),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.Column("UPDATED_USER", sa.String(length=20), nullable=True),
        sa.Column("UPDATED_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("DELETED", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["TAG_GROUP_CODE"], ["DM_TAG_GROUP.TAG_GROUP_CODE"], name="FK_DM_TAG_GROUP"),
        sa.PrimaryKeyConstraint("TAG_ID", name="PK_DM_TAG"),
    )
    op.create_index("IX_DM_TAG_GROUP", "DM_TAG", ["TAG_GROUP_CODE"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("IX_DM_TAG_GROUP", table_name="DM_TAG")
    op.drop_table("DM_TAG")
    op.drop_table("DM_TAG_GROUP")
    op.drop_table("DM_FUNC")
    op.drop_table("DM_CATEGORY")
    # ### end Alembic commands ###
