"""dm_create_review_audience_tables

Revision ID: 6a061732e842
Revises: 629c1a86b676
Create Date: 2026-08-06 11:03:46.841069

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a061732e842"
down_revision: Union[str, None] = "629c1a86b676"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DM_USER_TAG",
        sa.Column("USER_TAG_ID", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("USER_ID", sa.String(length=20), nullable=False),
        sa.Column("TAG_ID", sa.BigInteger(), nullable=False),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.Column("UPDATED_USER", sa.String(length=20), nullable=True),
        sa.Column("UPDATED_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("DELETED", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["TAG_ID"], ["DM_TAG.TAG_ID"], name="FK_DM_USER_TAG_TAG"),
        sa.PrimaryKeyConstraint("USER_TAG_ID", name="PK_DM_USER_TAG"),
        sa.UniqueConstraint("USER_ID", "TAG_ID", name="UQ_DM_USER_TAG_USER_TAG"),
    )
    op.create_index("IX_DM_USER_TAG_USER", "DM_USER_TAG", ["USER_ID"], unique=False)
    op.create_table(
        "DM_CHANGE_LOG",
        sa.Column("CHANGE_LOG_ID", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("DOC_ID", sa.String(length=20), nullable=False),
        sa.Column("VERSION_ID", sa.BigInteger(), nullable=True),
        sa.Column("OPERATION", sa.String(length=10), nullable=False),
        sa.Column("APPLICANT_USER_ID", sa.String(length=20), nullable=False),
        sa.Column("APPROVER_USER_ID", sa.String(length=20), nullable=False),
        sa.Column("OPERATION_TIME", sa.DateTime(timezone=True), nullable=False),
        sa.Column("NOTE", sa.Text(), nullable=True),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["DOC_ID"], ["DM_DOCUMENT.DOC_ID"], name="FK_DM_CHANGE_LOG_DOC"),
        sa.ForeignKeyConstraint(["VERSION_ID"], ["DM_DOC_VERSION.VERSION_ID"], name="FK_DM_CHANGE_LOG_VER"),
        sa.PrimaryKeyConstraint("CHANGE_LOG_ID", name="PK_DM_CHANGE_LOG"),
    )
    op.create_index("IX_DM_CHANGE_LOG_DOC", "DM_CHANGE_LOG", ["DOC_ID"], unique=False)
    op.create_index("IX_DM_CHANGE_LOG_TIME", "DM_CHANGE_LOG", ["OPERATION_TIME"], unique=False)
    op.create_table(
        "DM_REVIEW",
        sa.Column("REVIEW_ID", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("DOC_ID", sa.String(length=20), nullable=False),
        sa.Column("VERSION_ID", sa.BigInteger(), nullable=True),
        sa.Column("REVIEW_TYPE", sa.String(length=20), nullable=False),
        sa.Column("ASSIGNED_REVIEWER", sa.String(length=20), nullable=False),
        sa.Column("APPROVER_USER_ID", sa.String(length=20), nullable=True),
        sa.Column("STATUS", sa.String(length=20), nullable=False),
        sa.Column("SUBMIT_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.Column("COMPLETE_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("REASON", sa.Text(), nullable=True),
        sa.Column("OBSOLETE_FILE_NAME", sa.String(length=255), nullable=True),
        sa.Column("OBSOLETE_FILE_PATH", sa.String(length=500), nullable=True),
        sa.Column("OBSOLETE_FILE_SIZE", sa.BigInteger(), nullable=True),
        sa.Column("OBSOLETE_FILE_MIME", sa.String(length=100), nullable=True),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.Column("UPDATED_USER", sa.String(length=20), nullable=True),
        sa.Column("UPDATED_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("DELETED", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["DOC_ID"], ["DM_DOCUMENT.DOC_ID"], name="FK_DM_REVIEW_DOC"),
        sa.ForeignKeyConstraint(["VERSION_ID"], ["DM_DOC_VERSION.VERSION_ID"], name="FK_DM_REVIEW_VER"),
        sa.PrimaryKeyConstraint("REVIEW_ID", name="PK_DM_REVIEW"),
    )
    op.create_index("IX_DM_REVIEW_DOC", "DM_REVIEW", ["DOC_ID"], unique=False)
    op.create_index("IX_DM_REVIEW_REVIEWER", "DM_REVIEW", ["ASSIGNED_REVIEWER"], unique=False)
    op.create_index("IX_DM_REVIEW_STATUS", "DM_REVIEW", ["STATUS"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("IX_DM_REVIEW_STATUS", table_name="DM_REVIEW")
    op.drop_index("IX_DM_REVIEW_REVIEWER", table_name="DM_REVIEW")
    op.drop_index("IX_DM_REVIEW_DOC", table_name="DM_REVIEW")
    op.drop_table("DM_REVIEW")
    op.drop_index("IX_DM_CHANGE_LOG_TIME", table_name="DM_CHANGE_LOG")
    op.drop_index("IX_DM_CHANGE_LOG_DOC", table_name="DM_CHANGE_LOG")
    op.drop_table("DM_CHANGE_LOG")
    op.drop_index("IX_DM_USER_TAG_USER", table_name="DM_USER_TAG")
    op.drop_table("DM_USER_TAG")
    # ### end Alembic commands ###
