"""dp_create_notify_template

Revision ID: 6227f59bbd3f
Revises: 237bfdfaa3a7
Create Date: 2026-07-14 11:45:37.800868

建立 DP_NOTIFY_TEMPLATE 通知範本表。

異動說明：
- 影響 Table：DP_NOTIFY_TEMPLATE（新增）
- MODULE+TEMPLATE_CODE 複合 PK（PK_DP_NOTIFY_TEMPLATE）；BODY 用 TEXT
- VERSION 樂觀鎖版本欄位（ORM 綁定屬後續範本更新服務）
- DP 系統信 3 支種子（PWD_RESET / EMAIL_CHANGE_VERIFY / PWD_EXPIRY_REMIND）屬 T009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6227f59bbd3f'
down_revision: Union[str, None] = '237bfdfaa3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DP_NOTIFY_TEMPLATE',
    sa.Column('MODULE', sa.String(length=5), nullable=False),
    sa.Column('TEMPLATE_CODE', sa.String(length=30), nullable=False),
    sa.Column('TEMPLATE_NAME', sa.String(length=100), nullable=False),
    sa.Column('SUBJECT', sa.String(length=200), nullable=False),
    sa.Column('BODY', sa.Text(), nullable=False),
    sa.Column('VARIABLES', sa.String(length=500), nullable=True),
    sa.Column('CHANNEL', sa.String(length=10), nullable=False),
    sa.Column('IS_ENABLED', sa.Boolean(), nullable=False),
    sa.Column('IS_SYSTEM', sa.Boolean(), nullable=False),
    sa.Column('VERSION', sa.Integer(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('RES_ID', sa.String(length=30), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('MODULE', 'TEMPLATE_CODE', name='PK_DP_NOTIFY_TEMPLATE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DP_NOTIFY_TEMPLATE')
    # ### end Alembic commands ###
