"""dp_create_param_tables

Revision ID: 237bfdfaa3a7
Revises: b490652c02f4
Create Date: 2026-07-14 11:26:24.233431

建立 DP_PARAM_M 與 DP_PARAM_D 參數主檔/明細。

異動說明：
- 影響 Table：DP_PARAM_M（新增）、DP_PARAM_D（新增）
- DP_PARAM_M：PARAM_ID PK（PK_DP_PARAM_M）、BaseModel 標準欄位
- DP_PARAM_D：PARAM_ID+PARAM_KEY 複合 PK（PK_DP_PARAM_D）、FK_DP_PARAM_D_PARAM→DP_PARAM_M
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237bfdfaa3a7'
down_revision: Union[str, None] = 'b490652c02f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DP_PARAM_M',
    sa.Column('PARAM_ID', sa.String(length=50), nullable=False),
    sa.Column('PARAM_NAME', sa.String(length=100), nullable=False),
    sa.Column('PARAM_TYPE', sa.String(length=10), nullable=False),
    sa.Column('DETAIL_LOCK', sa.Boolean(), nullable=False),
    sa.Column('DESCRIPTION', sa.String(length=500), nullable=True),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('RES_ID', sa.String(length=30), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('PARAM_ID', name='PK_DP_PARAM_M')
    )
    op.create_table('DP_PARAM_D',
    sa.Column('PARAM_ID', sa.String(length=50), nullable=False),
    sa.Column('PARAM_KEY', sa.String(length=50), nullable=False),
    sa.Column('PARAM_VALUE', sa.String(length=500), nullable=True),
    sa.Column('SORT_ORDER', sa.Integer(), nullable=True),
    sa.Column('IS_ENABLED', sa.Boolean(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('RES_ID', sa.String(length=30), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PARAM_ID'], ['DP_PARAM_M.PARAM_ID'], name='FK_DP_PARAM_D_PARAM'),
    sa.PrimaryKeyConstraint('PARAM_ID', 'PARAM_KEY', name='PK_DP_PARAM_D')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DP_PARAM_D')
    op.drop_table('DP_PARAM_M')
    # ### end Alembic commands ###
