"""dm_create_document_tables

Revision ID: 629c1a86b676
Revises: 2d877f07412e
Create Date: 2026-08-06 10:36:06.950981

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "629c1a86b676"
down_revision: Union[str, None] = "2d877f07412e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DM_DOCUMENT",
        sa.Column("DOC_ID", sa.String(length=20), nullable=False),
        sa.Column("DOC_NAME", sa.String(length=200), nullable=False),
        sa.Column("CATEGORY_CODE", sa.String(length=10), nullable=False),
        sa.Column("FUNC_CODE", sa.String(length=10), nullable=True),
        sa.Column("CURRENT_VERSION_ID", sa.BigInteger(), nullable=True),
        sa.Column("STATUS", sa.String(length=20), nullable=False),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.Column("UPDATED_USER", sa.String(length=20), nullable=True),
        sa.Column("UPDATED_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("DELETED", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["CATEGORY_CODE"], ["DM_CATEGORY.CATEGORY_CODE"], name="FK_DM_DOCUMENT_CATEGORY"),
        sa.ForeignKeyConstraint(["FUNC_CODE"], ["DM_FUNC.FUNC_CODE"], name="FK_DM_DOCUMENT_FUNC"),
        sa.PrimaryKeyConstraint("DOC_ID", name="PK_DM_DOCUMENT"),
    )
    op.create_index("IX_DM_DOCUMENT_CATEGORY", "DM_DOCUMENT", ["CATEGORY_CODE"], unique=False)
    op.create_index("IX_DM_DOCUMENT_STATUS", "DM_DOCUMENT", ["STATUS"], unique=False)
    op.create_index(
        "UX_DM_DOCUMENT_MANUAL_FUNC",
        "DM_DOCUMENT",
        ["FUNC_CODE"],
        unique=True,
        postgresql_where=sa.text("\"CATEGORY_CODE\" = 'MANUAL' AND \"STATUS\" = 'PUBLISHED'"),
    )
    op.create_table(
        "DM_DOC_TAG",
        sa.Column("DOC_TAG_ID", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("DOC_ID", sa.String(length=20), nullable=False),
        sa.Column("TAG_ID", sa.BigInteger(), nullable=False),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.Column("UPDATED_USER", sa.String(length=20), nullable=True),
        sa.Column("UPDATED_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("DELETED", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["DOC_ID"], ["DM_DOCUMENT.DOC_ID"], name="FK_DM_DOC_TAG_DOC"),
        sa.ForeignKeyConstraint(["TAG_ID"], ["DM_TAG.TAG_ID"], name="FK_DM_DOC_TAG_TAG"),
        sa.PrimaryKeyConstraint("DOC_TAG_ID", name="PK_DM_DOC_TAG"),
        sa.UniqueConstraint("DOC_ID", "TAG_ID", name="UQ_DM_DOC_TAG_DOC_TAG"),
    )
    op.create_index("IX_DM_DOC_TAG_DOC", "DM_DOC_TAG", ["DOC_ID"], unique=False)
    op.create_index("IX_DM_DOC_TAG_TAG", "DM_DOC_TAG", ["TAG_ID"], unique=False)
    op.create_table(
        "DM_DOC_VERSION",
        sa.Column("VERSION_ID", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("DOC_ID", sa.String(length=20), nullable=False),
        sa.Column("VERSION_NO", sa.String(length=20), nullable=False),
        sa.Column("CHANGE_SUMMARY", sa.Text(), nullable=False),
        sa.Column("FILE_NAME", sa.String(length=255), nullable=False),
        sa.Column("FILE_PATH", sa.String(length=500), nullable=False),
        sa.Column("FILE_SIZE", sa.BigInteger(), nullable=False),
        sa.Column("FILE_MIME", sa.String(length=100), nullable=False),
        sa.Column("STATUS", sa.String(length=20), nullable=False),
        sa.Column("APPROVER_USER_ID", sa.String(length=20), nullable=True),
        sa.Column("PUBLISHED_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.Column("UPDATED_USER", sa.String(length=20), nullable=True),
        sa.Column("UPDATED_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("DELETED", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["DOC_ID"], ["DM_DOCUMENT.DOC_ID"], name="FK_DM_DOC_VERSION_DOC"),
        sa.PrimaryKeyConstraint("VERSION_ID", name="PK_DM_DOC_VERSION"),
        sa.UniqueConstraint("DOC_ID", "VERSION_NO", name="UQ_DM_DOC_VERSION_DOC_NO"),
    )
    op.create_index("IX_DM_DOC_VERSION_DOC", "DM_DOC_VERSION", ["DOC_ID"], unique=False)
    op.create_table(
        "DM_DOC_READ",
        sa.Column("READ_ID", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("DOC_ID", sa.String(length=20), nullable=False),
        sa.Column("VERSION_ID", sa.BigInteger(), nullable=False),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["DOC_ID"], ["DM_DOCUMENT.DOC_ID"], name="FK_DM_DOC_READ_DOC"),
        sa.ForeignKeyConstraint(["VERSION_ID"], ["DM_DOC_VERSION.VERSION_ID"], name="FK_DM_DOC_READ_VER"),
        sa.PrimaryKeyConstraint("READ_ID", name="PK_DM_DOC_READ"),
        sa.UniqueConstraint("DOC_ID", "VERSION_ID", "CREATED_USER", name="UQ_DM_DOC_READ_DOC_VER_USER"),
    )
    op.create_index("IX_DM_DOC_READ_DOC", "DM_DOC_READ", ["DOC_ID"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("IX_DM_DOC_READ_DOC", table_name="DM_DOC_READ")
    op.drop_table("DM_DOC_READ")
    op.drop_index("IX_DM_DOC_VERSION_DOC", table_name="DM_DOC_VERSION")
    op.drop_table("DM_DOC_VERSION")
    op.drop_index("IX_DM_DOC_TAG_TAG", table_name="DM_DOC_TAG")
    op.drop_index("IX_DM_DOC_TAG_DOC", table_name="DM_DOC_TAG")
    op.drop_table("DM_DOC_TAG")
    op.drop_index(
        "UX_DM_DOCUMENT_MANUAL_FUNC",
        table_name="DM_DOCUMENT",
        postgresql_where=sa.text("\"CATEGORY_CODE\" = 'MANUAL' AND \"STATUS\" = 'PUBLISHED'"),
    )
    op.drop_index("IX_DM_DOCUMENT_STATUS", table_name="DM_DOCUMENT")
    op.drop_index("IX_DM_DOCUMENT_CATEGORY", table_name="DM_DOCUMENT")
    op.drop_table("DM_DOCUMENT")
    # ### end Alembic commands ###
