"""dm_create_roles_tables

Revision ID: df37b7ba16b3
Revises: abe854a7da34
Create Date: 2026-08-06 10:22:22.434609

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df37b7ba16b3"
down_revision: Union[str, None] = "abe854a7da34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DM_USER_ROLE",
        sa.Column("DM_USER_ROLE_ID", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("USER_ID", sa.String(length=20), nullable=False),
        sa.Column("ROLE_CODE", sa.String(length=20), nullable=False),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.Column("UPDATED_USER", sa.String(length=20), nullable=True),
        sa.Column("UPDATED_DATE", sa.DateTime(timezone=True), nullable=True),
        sa.Column("DELETED", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("DM_USER_ROLE_ID", name="PK_DM_USER_ROLE"),
        sa.UniqueConstraint("USER_ID", "ROLE_CODE", name="UQ_DM_USER_ROLE_USER_ROLE"),
    )
    op.create_index("IX_DM_USER_ROLE_USER", "DM_USER_ROLE", ["USER_ID"], unique=False)
    op.create_table(
        "DM_USER_ROLE_LOG",
        sa.Column("LOG_ID", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("TARGET_USER_ID", sa.String(length=20), nullable=False),
        sa.Column("ROLE_CODE", sa.String(length=20), nullable=False),
        sa.Column("ACTION", sa.String(length=10), nullable=False),
        sa.Column("OPERATOR_USER_ID", sa.String(length=20), nullable=False),
        sa.Column("ACTION_TIME", sa.DateTime(timezone=True), nullable=False),
        sa.Column("CREATED_USER", sa.String(length=20), nullable=False),
        sa.Column("CREATED_DATE", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("LOG_ID", name="PK_DM_USER_ROLE_LOG"),
    )
    op.create_index("IX_DM_USER_ROLE_LOG_TARGET", "DM_USER_ROLE_LOG", ["TARGET_USER_ID"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("IX_DM_USER_ROLE_LOG_TARGET", table_name="DM_USER_ROLE_LOG")
    op.drop_table("DM_USER_ROLE_LOG")
    op.drop_index("IX_DM_USER_ROLE_USER", table_name="DM_USER_ROLE")
    op.drop_table("DM_USER_ROLE")
    # ### end Alembic commands ###
