"""dp_create_pwd_tables

Revision ID: d7db816ae523
Revises: 340572519872
Create Date: 2026-07-14 09:57:05.352226

建立 DP_PWD_RESET 與 DP_PWD_HIST 兩表。

異動說明：
- 影響 Table：DP_PWD_RESET（新增）、DP_PWD_HIST（新增）
- DP_PWD_RESET：TOKEN_HASH PK、FK_DP_PWD_RESET_USER→DP_USER、標準欄位（BaseModel）、
  索引 IX_DP_PWD_RESET_USER_TYPE_USED
- DP_PWD_HIST：USER_ID+SEQ_NO 複合 PK、FK_DP_PWD_HIST_USER→DP_USER、append-only（僅 CREATED_*）
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7db816ae523'
down_revision: Union[str, None] = '340572519872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DP_PWD_HIST',
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('SEQ_NO', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('PWD_HASH', sa.String(length=100), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['USER_ID'], ['DP_USER.USER_ID'], name='FK_DP_PWD_HIST_USER'),
    sa.PrimaryKeyConstraint('USER_ID', 'SEQ_NO', name='PK_DP_PWD_HIST')
    )
    op.create_table('DP_PWD_RESET',
    sa.Column('TOKEN_HASH', sa.String(length=64), nullable=False),
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('TOKEN_TYPE', sa.String(length=20), nullable=False),
    sa.Column('NEW_EMAIL', sa.String(length=255), nullable=True),
    sa.Column('EXPIRES_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('USED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('RES_ID', sa.String(length=30), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['USER_ID'], ['DP_USER.USER_ID'], name='FK_DP_PWD_RESET_USER'),
    sa.PrimaryKeyConstraint('TOKEN_HASH', name='PK_DP_PWD_RESET')
    )
    op.create_index('IX_DP_PWD_RESET_USER_TYPE_USED', 'DP_PWD_RESET', ['USER_ID', 'TOKEN_TYPE', 'USED_DATE'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IX_DP_PWD_RESET_USER_TYPE_USED', table_name='DP_PWD_RESET')
    op.drop_table('DP_PWD_RESET')
    op.drop_table('DP_PWD_HIST')
    # ### end Alembic commands ###
