"""dp_create_audit_log

Revision ID: b490652c02f4
Revises: d7db816ae523
Create Date: 2026-07-14 10:24:40.998723

建立 DP_AUDIT_LOG 操作歷程表。

異動說明：
- 影響 Table：DP_AUDIT_LOG（新增，append-only 僅 CREATED_*）
- LOG_ID BIGINT Identity PK（PK_DP_AUDIT_LOG）；BEFORE/AFTER_VALUE 用 TEXT 存 JSON（非 JSONB）
- ROW_HASH 鏈式完整性雜湊欄位（計算邏輯屬 T011 稽核服務）
- 3 索引：CREATED_DATE / (CREATED_USER,CREATED_DATE) / (MODULE,ACTION_TYPE,CREATED_DATE)
- 落地要求（部署/ops 層，非本 migration）：應用 DB 帳號對本表僅 GRANT INSERT / SELECT
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b490652c02f4'
down_revision: Union[str, None] = 'd7db816ae523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DP_AUDIT_LOG',
    sa.Column('LOG_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('MODULE', sa.String(length=5), nullable=False),
    sa.Column('FUNC_NAME', sa.String(length=50), nullable=False),
    sa.Column('ACTION_TYPE', sa.String(length=10), nullable=False),
    sa.Column('TARGET_ID', sa.String(length=100), nullable=True),
    sa.Column('RESULT', sa.String(length=10), nullable=False),
    sa.Column('DESCRIPTION', sa.String(length=500), nullable=True),
    sa.Column('SOURCE_IP', sa.String(length=45), nullable=True),
    sa.Column('BEFORE_VALUE', sa.Text(), nullable=True),
    sa.Column('AFTER_VALUE', sa.Text(), nullable=True),
    sa.Column('ROW_HASH', sa.String(length=64), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('LOG_ID', name='PK_DP_AUDIT_LOG')
    )
    op.create_index('IX_DP_AUDIT_LOG_CREATED_DATE', 'DP_AUDIT_LOG', ['CREATED_DATE'], unique=False)
    op.create_index('IX_DP_AUDIT_LOG_CREATED_USER_DATE', 'DP_AUDIT_LOG', ['CREATED_USER', 'CREATED_DATE'], unique=False)
    op.create_index('IX_DP_AUDIT_LOG_MODULE_ACTION_DATE', 'DP_AUDIT_LOG', ['MODULE', 'ACTION_TYPE', 'CREATED_DATE'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IX_DP_AUDIT_LOG_MODULE_ACTION_DATE', table_name='DP_AUDIT_LOG')
    op.drop_index('IX_DP_AUDIT_LOG_CREATED_USER_DATE', table_name='DP_AUDIT_LOG')
    op.drop_index('IX_DP_AUDIT_LOG_CREATED_DATE', table_name='DP_AUDIT_LOG')
    op.drop_table('DP_AUDIT_LOG')
    # ### end Alembic commands ###
