"""dp_create_email_log

Revision ID: 53ffc92cab2d
Revises: 6227f59bbd3f
Create Date: 2026-07-14 14:02:20.262753

建立 DP_EMAIL_LOG 寄件 outbox 表。

異動說明：
- 影響 Table：DP_EMAIL_LOG（新增；可更新狀態、永不刪除 → 含 UPDATED_*、無 DELETED / 無 RES_ID）
- MESSAGE_ID BIGINT Identity PK（PK_DP_EMAIL_LOG）；BODY 用 TEXT
- 索引 IX_DP_EMAIL_LOG_STATUS_CREATED (STATUS, CREATED_DATE) 供 worker 輪詢
- 使用新基底 BaseModelNoDelete（outbox/log 專用）
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ffc92cab2d'
down_revision: Union[str, None] = '6227f59bbd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DP_EMAIL_LOG',
    sa.Column('MESSAGE_ID', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('MODULE', sa.String(length=5), nullable=False),
    sa.Column('TEMPLATE_CODE', sa.String(length=30), nullable=False),
    sa.Column('CALLER_MODULE', sa.String(length=5), nullable=False),
    sa.Column('RECIPIENT', sa.String(length=255), nullable=False),
    sa.Column('SUBJECT', sa.String(length=200), nullable=False),
    sa.Column('BODY', sa.Text(), nullable=False),
    sa.Column('STATUS', sa.String(length=10), nullable=False),
    sa.Column('RETRY_COUNT', sa.Integer(), nullable=False),
    sa.Column('ERROR_MSG', sa.String(length=500), nullable=True),
    sa.Column('SENT_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('MESSAGE_ID', name='PK_DP_EMAIL_LOG')
    )
    op.create_index('IX_DP_EMAIL_LOG_STATUS_CREATED', 'DP_EMAIL_LOG', ['STATUS', 'CREATED_DATE'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IX_DP_EMAIL_LOG_STATUS_CREATED', table_name='DP_EMAIL_LOG')
    op.drop_table('DP_EMAIL_LOG')
    # ### end Alembic commands ###
