"""dp_create_dp_user

Revision ID: 340572519872
Revises:
Create Date: 2026-07-13 17:05:09.781392

建立 DP_USER 使用者主檔（不含 SITE）。

異動說明：
- 影響 Table：DP_USER（新增）
- 業務欄位 11 個 + BaseModel 標準欄位（CREATED_* / UPDATED_* / RES_ID / DELETED，無 SITE）
- 約束：PK_DP_USER、UQ_DP_USER_EMAIL（EMAIL 不加密）
- 不建 DP_SESSION（無 Refresh Token，見 research §1）
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340572519872'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DP_USER',
    sa.Column('USER_ID', sa.String(length=20), nullable=False),
    sa.Column('EMAIL', sa.String(length=255), nullable=False),
    sa.Column('PWD_HASH', sa.String(length=100), nullable=False),
    sa.Column('USER_NAME', sa.String(length=50), nullable=False),
    sa.Column('STATUS', sa.String(length=10), nullable=False),
    sa.Column('LOGIN_FAIL_COUNT', sa.Integer(), nullable=False),
    sa.Column('LOCKED_UNTIL', sa.DateTime(timezone=True), nullable=True),
    sa.Column('LAST_LOGIN_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('PENDING_EMAIL', sa.String(length=255), nullable=True),
    sa.Column('PWD_CHANGED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('MUST_CHANGE_PWD', sa.Boolean(), nullable=False),
    sa.Column('CREATED_USER', sa.String(length=20), nullable=False),
    sa.Column('CREATED_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UPDATED_USER', sa.String(length=20), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(timezone=True), nullable=True),
    sa.Column('RES_ID', sa.String(length=30), nullable=True),
    sa.Column('DELETED', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('USER_ID', name='PK_DP_USER'),
    sa.UniqueConstraint('EMAIL', name='UQ_DP_USER_EMAIL')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DP_USER')
    # ### end Alembic commands ###
